# Generated by Django 3.0.6 on 2020-06-08 06:56

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='class_room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, verbose_name='نام کلاس')),
                ('class_number', models.SlugField(unique=True, verbose_name='شماره کلاس')),
                ('slug', models.SlugField(max_length=100, unique=True, verbose_name='آدرس کلاس')),
                ('section', models.CharField(max_length=200, verbose_name='بخش')),
                ('room', models.CharField(max_length=200, verbose_name='اتاق')),
                ('subject', models.CharField(max_length=200, verbose_name='موضوع')),
                ('startdate', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ شروع کلاس')),
                ('created_time', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد')),
                ('finished_time', models.DateTimeField(default=django.utils.timezone.now, verbose_name='تاریخ پایان کلاس')),
                ('updated_time', models.DateTimeField(auto_now=True, verbose_name='تاریخ آخرین آپدیت')),
                ('status', models.CharField(choices=[('public', 'عمومی'), ('private', 'خصوصی')], max_length=7, verbose_name='وضعیت انتشار')),
            ],
            options={
                'verbose_name': 'کلاس',
                'verbose_name_plural': 'کلاس\u200cها',
            },
        ),
        migrations.CreateModel(
            name='Headings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('headings_name', models.CharField(max_length=200, null=True, verbose_name='عنوان')),
                ('headingsـpost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='headings', to='classroom.class_room', verbose_name='کلاس')),
            ],
            options={
                'verbose_name': 'عناوین',
                'verbose_name_plural': 'عناوین',
            },
        ),
        migrations.CreateModel(
            name='SubHeadings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subheadings_name', models.CharField(max_length=200, null=True, verbose_name='زیر عنوان')),
                ('subheadings_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subheadings', to='classroom.Headings', verbose_name='عنوان')),
            ],
            options={
                'verbose_name': 'زیر عنوان',
                'verbose_name_plural': 'زیر عناوین',
            },
        ),
        migrations.CreateModel(
            name='EnrolledTeacher',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('previous_attempts', models.IntegerField(default=0)),
                ('classroom', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classroom_enrollteacher', to='classroom.class_room', verbose_name='نام کلاس')),
                ('teacher_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='teachers', to='account.Profile', verbose_name='نام کاربری')),
            ],
            options={
                'verbose_name': 'استاد کلاس',
                'verbose_name_plural': 'اساتید کلاس',
            },
        ),
        migrations.CreateModel(
            name='Enrolled',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('previous_attempts', models.IntegerField(default=0)),
                ('classroom', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classroom_enroll', to='classroom.class_room', verbose_name='نام کلاس')),
                ('student_profile', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='students', to='account.Profile', verbose_name='نام کاربری')),
            ],
            options={
                'verbose_name': 'دانش آموز کلاس',
                'verbose_name_plural': 'دانش آموزان کلاس',
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=80, null=True, verbose_name='نام')),
                ('body', models.TextField(null=True, verbose_name='متن')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('active', models.BooleanField(default=True)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='classroom.class_room', verbose_name='نام کلاس')),
            ],
            options={
                'verbose_name': 'گفتگو',
                'verbose_name_plural': 'گفتگوها',
                'ordering': ['created_on'],
            },
        ),
        migrations.CreateModel(
            name='Classworks',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('classworks_name', models.CharField(max_length=80, null=True, verbose_name='نام مبحث')),
                ('classworks_body', models.TextField(null=True, verbose_name='متن')),
                ('classworks_created_on', models.DateTimeField(auto_now_add=True)),
                ('classworks_active', models.BooleanField(default=True)),
                ('classworks_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='classworks', to='classroom.class_room', verbose_name='نام کلاس')),
            ],
            options={
                'verbose_name': 'تکلیف',
                'verbose_name_plural': 'تکالیف',
                'ordering': ['classworks_created_on'],
            },
        ),
        migrations.AddField(
            model_name='class_room',
            name='students',
            field=models.ManyToManyField(related_name='classstudents', through='classroom.Enrolled', to='account.Profile'),
        ),
        migrations.AddField(
            model_name='class_room',
            name='teachers',
            field=models.ManyToManyField(related_name='classteachers', through='classroom.EnrolledTeacher', to='account.Profile'),
        ),
    ]
