# Generated by Django 3.0.6 on 2020-06-10 13:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('classroom', '0002_class_room_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='classworks',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='classwork_creator', to=settings.AUTH_USER_MODEL, verbose_name='نام استاد'),
        ),
        migrations.AddField(
            model_name='comment',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='comment_creator', to=settings.AUTH_USER_MODEL, verbose_name='نام نظر\u200cدهنده'),
        ),
        migrations.AlterField(
            model_name='class_room',
            name='creator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='class_creator', to=settings.AUTH_USER_MODEL, verbose_name='ایجادکننده کلاس'),
        ),
    ]
