# Generated by Django 3.0.6 on 2020-06-11 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20200610_1752'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolled',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='enrolledteacher',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
