# Generated by Django 3.0.6 on 2020-06-11 15:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0005_auto_20200611_1925'),
    ]

    operations = [
        migrations.AlterField(
            model_name='enrolledteacher',
            name='classroom',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='classroom_enrollteacher', to='classroom.class_room', verbose_name='نام کلاس'),
        ),
    ]
