# Generated by Django 3.0.6 on 2020-06-11 15:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20200611_1931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='enrolledteacher',
            old_name='classroom',
            new_name='tclassroom',
        ),
    ]
