# Generated by Django 3.0.6 on 2021-01-10 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='national_code',
            field=models.IntegerField(max_length=10, null=True, unique=True, verbose_name='کد ملی'),
        ),
        migrations.AddField(
            model_name='profile',
            name='phone_number',
            field=models.CharField(max_length=11, null=True, unique=True, verbose_name='شماره همراه'),
        ),
    ]
